from enum import Enum


class BinaryBits(Enum):
    SIGN_BITS_LONG = 1
    TIMESTAMP_BITS_LONG = 41
    SEQUANCE_NUMBER_BITS_LONG = 12
    DATACENTER_ID_TOTAL_LONG = 5
    MACHINE_ID_TOTAL_LONG = 5

    DATACENTER_ID_TOTAL_BITS = 31
    MACHINE_ID_TOTAL_BITS = 31
